package imagemanage;

import javax.swing.ImageIcon;

/**
 *
 * @author ThiagoAugustus
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        try{
            ImageIcon icon = new ImageIcon("src/img/image.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+80);
            this.label2.setIcon(icon);
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        btCinza = new javax.swing.JButton();
        btBi = new javax.swing.JButton();
        btZIQ = new javax.swing.JButton();
        btZIL = new javax.swing.JButton();
        btZUQ = new javax.swing.JButton();
        btZUL = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCinza.setText("Cinza");
        btCinza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCinzaActionPerformed(evt);
            }
        });

        btBi.setText("Bipolarização");
        btBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBiActionPerformed(evt);
            }
        });

        btZIQ.setText("ZIQ");
        btZIQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZIQActionPerformed(evt);
            }
        });

        btZIL.setText("ZIL");
        btZIL.setMaximumSize(new java.awt.Dimension(51, 23));
        btZIL.setMinimumSize(new java.awt.Dimension(51, 23));
        btZIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZILActionPerformed(evt);
            }
        });

        btZUQ.setText("ZUQ");
        btZUQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZUQActionPerformed(evt);
            }
        });

        btZUL.setText("ZUL");
        btZUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZULActionPerformed(evt);
            }
        });

        btReset.setText("Reset");
        btReset.setToolTipText("");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btZIQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btZIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btZUL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btZUQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCinza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btZIQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btZIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btZUQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btZUL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCinzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCinzaActionPerformed
        // TODO add your handling code here:
        Imagem img = new Imagem();
        img.loadImage("image.jpg").grayImage("cinza.jpg");
        try{
            ImageIcon icon = new ImageIcon("cinza.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+80);
            this.label2.setIcon(icon);
            this.revalidate();
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btCinzaActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        try{
            ImageIcon icon = new ImageIcon("src/img/image.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+80);
            this.label2.setIcon(icon);
            this.revalidate();
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btResetActionPerformed

    private void btBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBiActionPerformed
        // TODO add your handling code here:
        Imagem img = new Imagem();
        img.loadImage("image.jpg").binarizacao("bibolarizacao.jpg",100);
        try{
            ImageIcon icon = new ImageIcon("bibolarizacao.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+80);
            this.label2.setIcon(icon);
            this.revalidate();
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btBiActionPerformed

    private void btZIQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZIQActionPerformed
        // TODO add your handling code here:
        Imagem img = new Imagem();
        img.loadImage("image.jpg").zoomInQuadrado("zoominq.jpg");
        try{
            ImageIcon icon = new ImageIcon("zoominq.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+80);
            this.label2.setIcon(icon);
            this.revalidate();
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btZIQActionPerformed

    private void btZILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZILActionPerformed
        // TODO add your handling code here:
        Imagem img = new Imagem();
        img.loadImage("image.jpg").zoomInLinear("zoominl.jpg");
        try{
            ImageIcon icon = new ImageIcon("zoominl.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+80);
            this.label2.setIcon(icon);
            this.revalidate();
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btZILActionPerformed

    private void btZUQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZUQActionPerformed
        // TODO add your handling code here:
        Imagem img = new Imagem();
        img.loadImage("image.jpg").zoomOutQuadratica("zoomoutq.jpg");
        try{
            ImageIcon icon = new ImageIcon("zoomoutq.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+160);
            this.label2.setIcon(icon);
            this.revalidate();
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btZUQActionPerformed

    private void btZULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZULActionPerformed
        // TODO add your handling code here:
        Imagem img = new Imagem();
        img.loadImage("image.jpg").zoomOutLinear("zoomoutl.jpg");
        try{
            ImageIcon icon = new ImageIcon("zoomoutl.jpg");
            this.setSize(icon.getIconWidth()+170, icon.getIconHeight()+160);
            this.label2.setIcon(icon);
            this.revalidate();
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btZULActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBi;
    private javax.swing.JButton btCinza;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btZIL;
    private javax.swing.JButton btZIQ;
    private javax.swing.JButton btZUL;
    private javax.swing.JButton btZUQ;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label2;
    // End of variables declaration//GEN-END:variables
}
